{
    "type": "bundle",
    "id": "bundle--594dd5a4-83e5-44eb-b04f-1165cbee8db1",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--680839d9-a5e7-46c2-b66d-d1b58c0847a4",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:30.485115Z",
            "modified": "2021-03-13T20:12:30.485115Z",
            "name": "CVE-2020-24372",
            "description": "LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-24372"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}