{
    "type": "bundle",
    "id": "bundle--f32dde13-2c6e-4d52-a893-e565024ee9a4",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--31fbcfc4-37c3-425d-b5c1-04290c48f8d6",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:26.179879Z",
            "modified": "2021-03-13T20:12:26.179879Z",
            "name": "CVE-2020-15701",
            "description": "An unhandled exception in check_ignored() in apport/report.py can be exploited by a local attacker to cause a denial of service. If the mtime attribute is a string value in apport-ignore.xml, it will trigger an unhandled exception, resulting in a crash. Fixed in 2.20.1-0ubuntu2.24, 2.20.9-0ubuntu7.16, 2.20.11-0ubuntu27.6.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-15701"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}