{
    "type": "bundle",
    "id": "bundle--03ea1129-9875-466f-8744-511576f2e181",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0c9ebbed-e46f-4873-9b71-63592f98f0a3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-06-08T00:39:47.252725Z",
            "modified": "2021-06-08T00:39:47.252725Z",
            "name": "CVE-2020-36387",
            "description": "An issue was discovered in the Linux kernel before 5.8.2. fs/io_uring.c has a use-after-free related to io_async_task_func and ctx reference holding, aka CID-6d816e088c35.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-36387"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}