{
    "type": "bundle",
    "id": "bundle--d8a80159-f408-4d1a-ba2f-df03d422783d",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ea960d8c-f16c-49a1-a7c5-4282ac8b8114",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:52.021887Z",
            "modified": "2021-03-13T20:11:52.021887Z",
            "name": "CVE-2019-20432",
            "description": "In the Lustre file system before 2.12.3, the mdt module has an out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. mdt_file_secctx_unpack does not validate the value of name_size derived from req_capsule_get_size.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-20432"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}