{
    "type": "bundle",
    "id": "bundle--ec20ec2a-8931-4194-bff1-788d19952a20",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--19dd6926-5c72-4926-901f-bb888d044d54",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:10:15.304915Z",
            "modified": "2021-03-13T20:10:15.304915Z",
            "name": "CVE-2008-7264",
            "description": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2008-7264"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}