{
    "type": "bundle",
    "id": "bundle--22aa9095-2b05-44a7-9d7b-e721b140c4b7",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c3bc095c-881b-49ba-ae1d-b420884acc34",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:50.340209Z",
            "modified": "2021-03-13T20:11:50.340209Z",
            "name": "CVE-2019-14235",
            "description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-14235"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}