{
    "type": "bundle",
    "id": "bundle--fe9e8805-9fa5-469a-8a5e-2a6371e4beab",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--8f4c6e38-4d37-4ead-9681-63b4b6d5f8f3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:57.49494Z",
            "modified": "2021-03-13T20:12:57.49494Z",
            "name": "CVE-2018-14449",
            "description": "An issue was discovered in libgig 4.1.0. There is an out of bounds read in gig::File::UpdateChunks in gig.cpp.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-14449"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}