{
    "type": "bundle",
    "id": "bundle--f020fb2c-5f07-4ab4-9444-1bdf5e3bf89b",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--e178ad41-22ba-4ac6-bc0e-ff3d95a39682",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:40.894849Z",
            "modified": "2021-03-13T20:12:40.894849Z",
            "name": "CVE-2020-29242",
            "description": "dhowden tag before 2020-11-19 allows \"panic: runtime error: index out of range\" via readPICFrame.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-29242"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}