{
    "type": "bundle",
    "id": "bundle--85e38018-78c4-409a-adfb-42e887535ccd",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--abc55372-ec2a-4784-a5fb-e92e0cab38bb",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:13:02.044569Z",
            "modified": "2021-03-13T20:13:02.044569Z",
            "name": "CVE-2018-10879",
            "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-10879"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}