{
    "type": "bundle",
    "id": "bundle--20b34bcc-f93a-4572-8401-7f11f781a870",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0b3de2f0-6137-4dd3-aa84-4ab390870c99",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:30.314133Z",
            "modified": "2021-03-13T20:12:30.314133Z",
            "name": "CVE-2020-9991",
            "description": "This issue was addressed with improved checks. This issue is fixed in macOS Big Sur 11.0.1, watchOS 7.0, iOS 14.0 and iPadOS 14.0, iCloud for Windows 7.21, tvOS 14.0. A remote attacker may be able to cause a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-9991"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}