{
    "type": "bundle",
    "id": "bundle--49169896-94e8-469c-a10a-0e6398747093",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--7f2daf89-b4c4-42fe-b70e-439c2111dd77",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:13:07.012148Z",
            "modified": "2021-03-13T20:13:07.012148Z",
            "name": "CVE-2018-16438",
            "description": "An issue was discovered in the HDF HDF5 1.8.20 library. There is an out of bounds read in H5L_extern_query at H5Lexternal.c.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-16438"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}