{
    "type": "bundle",
    "id": "bundle--8070ef81-544a-4852-8fe1-9f9b8404c896",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--1afca96e-c461-4742-a080-07e69dcc84bd",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:29.639861Z",
            "modified": "2021-03-13T20:12:29.639861Z",
            "name": "CVE-2020-9917",
            "description": "This issue was addressed with improved checks. This issue is fixed in iOS 13.6 and iPadOS 13.6. A remote attacker may be able to cause a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-9917"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}